-- Clear database

-- Delete all database tables
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS food_groups CASCADE;
DROP TABLE IF EXISTS ingredients CASCADE;
DROP TABLE IF EXISTS thematic_categories CASCADE;
DROP TABLE IF EXISTS steps CASCADE;
DROP TABLE IF EXISTS equipment CASCADE;
DROP TABLE IF EXISTS cuisines CASCADE;
DROP TYPE IF EXISTS DIFFICULTY CASCADE;
DROP TYPE IF EXISTS MEAL_GROUP CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS recipe_equipment CASCADE;
DROP TABLE IF EXISTS recipe_ingredients CASCADE;
DROP TABLE IF EXISTS recipe_steps CASCADE;
DROP TABLE IF EXISTS recipe_tips CASCADE;
DROP TABLE IF EXISTS recipe_tags CASCADE;
DROP TABLE IF EXISTS recipe_thematic_categories CASCADE;
DROP TYPE IF EXISTS JOB_TITLE CASCADE;
DROP TABLE IF EXISTS chefs CASCADE;
DROP TABLE IF EXISTS episodes CASCADE;
DROP TABLE IF EXISTS marks CASCADE;
DROP TYPE IF EXISTS COOKING_TYPE CASCADE;
DROP TABLE IF EXISTS episodes_cuisines CASCADE;
DROP TABLE IF EXISTS episodes_cuisines_chefs CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS USER_ROLE CASCADE;
DROP TABLE IF EXISTS judges CASCADE;

-- Path: queries/test.sql